% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 03-May-2017 21:58:44
%
% This script assumes these variables are defined:
%
%   cancerInputs - input data.
%   cancerTargets - target data.

load('mnist_train.mat');
labels = [];
for i = 1:10
    labels = [labels, train_labels == i];
end

x = train_X';
t = labels';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'traingd';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = 12;
net = patternnet(hiddenLayerSize, trainFcn);
net.trainParam.lr = 0.1; 
net.trainParam.epochs = 1000;

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y);
tind = vec2ind(t);
yind = vec2ind(y);
percentErrors = sum(tind ~= yind)/numel(tind);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

%calculate error
for i = 1:60000
    if (y(i) < 0.5) && (y(i) > 0)
        y(i) = 0;
    elseif (y(i) > 0.5) && (y(i) <= 1)
        y(i) = 1;
    else
        y(i) = -1;
    end
end

trainErrNum = 0;
testErrNum = 0;
for i = 1:42000
    if y(i) ~= t(i)
        trainErrNum = trainErrNum+1;
    end
end
for i = 51001:60000
    if y(i) ~= t(i)
        testErrNum = testErrNum+1;
    end
end
trainErrPercent = trainErrNum/60000; 
testErrPercent = testErrNum/10000; 

